#! /usr/bin/env bash

export PROJECT=`pwd`
export PROJ_NAME="camera"

if [ ! $PROJ_NAME == ${PROJECT##*/} ]; then
    echo "This script must be run from the project directory. See README."
    exit
fi

if [ ! -f bin/activate ] && [ ! -f Scripts/activate ]; then
    $PROJECT/utils/create
fi

bash --rcfile $PROJECT/utils/rcfile
stty sane
