#!/usr/bin/env python
import pickle
import sys
import argparse

DEFAULT_CFG_FILE='camera.cfg'
DEFAULT_CFG_NAME='Default Config'
DEFAULT_CFG_PORT='/dev/ttyUSB0'

MAX_PAN = 800
MIN_PAN = 0
MAX_TILT = 200
MIN_TILT = 0
MAX_ZOOM = 2880
MIN_ZOOM = 0
RESET_PAN = 410
RESET_TILT = 125
RESET_ZOOM = 0

parser = argparse.ArgumentParser(
    description='Create a default configuration file for the camera controller.')
parser.add_argument('-f', dest="fname", default='camera.cfg', 
                    help="name of the configuration file to use", 
                    type=str, required=True)
parser.add_argument('-p', dest="port", default='/dev/ttyUSB0', 
                    help="name of the serial port to use", 
                    type=str, required=True)
parser.add_argument('-c', dest="cname", default='Default Config', 
                    help="name of the camera to use", 
                    type=str, required=True)
args = parser.parse_args()

if len(sys.argv) > 1:
    cam_name = sys.argv[1]
else:
    cam_name = DEFAULT_CFG_NAME

data = {}
data['cam_name'] = args.cname
data['cam_port'] = args.port

data['presets'] = {}

data['presets']['Default'] = {}
data['presets']['Default']['pan'] = RESET_PAN
data['presets']['Default']['tilt'] = RESET_TILT
data['presets']['Default']['zoom'] = RESET_ZOOM

# data['presets']['test 1'] = {}
# data['presets']['test 1']['pan'] = 510
# data['presets']['test 1']['tilt'] = 120
# data['presets']['test 1']['zoom'] = 1000

# data['presets']['test 2'] = {}
# data['presets']['test 2']['pan'] = 85
# data['presets']['test 2']['tilt'] = 20
# data['presets']['test 2']['zoom'] = 1500

# data['presets']['test 3'] = {}
# data['presets']['test 3']['pan'] = 700
# data['presets']['test 3']['tilt'] = 400
# data['presets']['test 3']['zoom'] = 0

# data['presets']['test 4'] = {}
# data['presets']['test 4']['pan'] = 400
# data['presets']['test 4']['tilt'] = 20
# data['presets']['test 4']['zoom'] = 2000

with open(args.fname, "wb") as fh:
    pickle.dump(data, fh)
